### ISSUE TITLE
make: *** No rule to make target 'examples/color/generated_assets/cmoc_udc_25_tiles_and_fonts.s', needed by 'coco'.  Stop.

### ISSUE THREAD

**Issue by 6809-user** [Fabrizio-Caruso/CROSS-LIB#276]
some target files do not get built.
If i try to xl build all coco, getting a lot of missing targets for this system, compared to c64 system.
I tried xl build all all and get better resaults.
coco did not have many programs.
Is this normal, or did i miss something.
I thought all targets would be built.

**Comment by Fabrizio-Caruso** [comment]
@6809-user Thanks for reporting the issue. There may be a bug in my scripts. I am going to check it and fix it.
By the way, `xl build all coco` is not correct.
The correct command is:
```xl build <name of the game> <target name or all>``` 
or just the same without `build`: 
```xl <name of the game> <target name or all>``` 
Current games provided with Cross-Lib are: `chase`, `shoot`, `bomber`, `snake`, `horde`
There are also many examples and other games can be coded by the user.

In order to build a game for a target with the Motorola 6809, you need to install the CMOC compiler.

P.S.: You can also find the prebuilt games in the release section but they do not necessarily use the very latest version.

**Comment by Fabrizio-Caruso** [comment]
@6809-user could you please pull the latest version of Cross-Lib and try:
```xl games coco``` ?

**Comment by 6809-user** [comment]
Ok, will do,
just cloned new cross-lib git.
I am running debian ( bullseye )
Only found 2 games in build folder: Xbomber and Xshoot.

The last 5 lines of output from "xl games coco"
rm -rf ../build/Xshoot_coco_no_gfx.dsk
cp ../build/Xshoot_coco_no_gfx.bin XCHASE.BIN
../tools/cmoc/coco/file2dsk XCHASE.BIN
make: ../tools/cmoc/coco/file2dsk: No such file or directory
make: *** [games/shoot/Makefile.shoot:1137: coco_no_gfx] Error 127

I seem to have a windows file2dsk.exe in tools/cmoc/coco, had a look at the README,
I guess no linux binary yet for that tool.

**Comment by Fabrizio-Caruso** [comment]
@6809-user Indeed for Windows I use those tools. For Linux/FreeBSD I only the binaries. I will include the Linux versions of the tools in the future but the raw binaries should build even without those tools.
You should get all the 5 games, though.
I am going to fix the issues.
Please keep reporting bugs. I am more then willing to fix them.

**Comment by Fabrizio-Caruso** [comment]
@6809-user I have just fix the coco build for the 3 failing games (chase, snake, horde).
So far, I have tested them under Cygwin/Windows. I still need to test them under Linux/FreeBSD.
Please pull (git pull) the latest version.
Thanks again for reporting problems!

**Comment by 6809-user** [comment]
The new pull works fine, the other 3 games got built.
probably a non-issue but, 
I noticed that running between x64 (vice) and xroar that running "horde" the sound is very high pitched in vice than xroar.
(mostly getting clicks when running xhorde)
Was the sound supposed to be consistent between the builds, or is that just my setup?
Currently messing around in sound/sid settings in x64.

**Comment by Fabrizio-Caruso** [comment]
@6809-user Thanks to you I have spotted and fixed some bugs! Please keep on reporting issues.

I also accept code suggestions and suggestions for improvements.

The sound is not consistent (yet) and is *very* limited (just some effects).
The problem here is (my) limited time because I have hundreds of different targets. So I only implemented a few effects that should sound vaguely similar but are not supposed to be very close. I can improve them.

I will keep testing this issue a bit more maybe for a day. I will close it if you do not report other build problems on the CoCo.

By the way, I also support other Motorola 6809 targets such as the Dragon and the French Thomson Mo, Thomson To series and  the Olivetti Prodest 128.

**Comment by Fabrizio-Caruso** [comment]
@6809-user I have been able to run build the 5 coco games and 12 coco examples on both Windows and Ubuntu. I am closing this issue.

Thanks a lot.

Please keep on reporting bugs and suggestions.

**Comment by Fabrizio-Caruso** [comment]
@6809-user By the way, may I ask you how you got to know about Cross-Lib ?

**Comment by 6809-user** [comment]
By way of searching the web and found your git repository.
