### ISSUE TITLE
Xsnake_coleco.rom Not Working

### ISSUE THREAD

**Issue by ikrananka** [Fabrizio-Caruso/CROSS-LIB#284]
Just tried to run Xsnake_coleco.rom (13 May 2021) and all I get is a black screen.

**Comment by Fabrizio-Caruso** [comment]
Thanks for reporting the issue. So you used the old precompiled ROM. How did you test it? Which emulator version? Did the other games work?

**Comment by ikrananka** [comment]
Yes, it was the old precompiled ROM.  I tested it using the latest versions of CoolCV (v0.6.9) and ColEm (v5.5).  The other two games, Cross Chase and Cross Horde both work.

**Comment by Fabrizio-Caruso** [comment]
Thanks. I will try the 5 games with the latest versions of Cross-Lib and Z88DK and see if they work and what might be wrong.
Cross Shoot and Cross Bomber can also be built for the Coleco and Coleco Adam.

**Comment by ikrananka** [comment]
Excellent - I'll look forward to trying them out again when they're available.

**Comment by Fabrizio-Caruso** [comment]
I have a hunch. Maybe the Coleco does not have enough RAM. I can do something about it...

**Comment by Fabrizio-Caruso** [comment]
@ikrananka I will also tune the speed of the other games. X Horde seems to slow.

**Comment by ikrananka** [comment]
Great, hoping this helps improve the cross compiler => Coleco 👍

**Comment by Fabrizio-Caruso** [comment]
I have created a new release only for the Coleco versions of 4 out of 5 games:
https://github.com/Fabrizio-Caruso/CROSS-LIB/releases/tag/coleco

Some of the games have just been slightly tuned for the Coleco.
Sound is still missing and I need to figure it out.

The issue with XSnake is a hardware limitation of the Coleco console, which is reached by the XSnake code because it uses too much RAM to store the objects on the screen. So an ugly workaround to get it to work is to make the screen very small. A better solution would require a complex change in the code. Remark: the game code is the *very same* for 200 computers and consoles and it is hardware-agnostic. Cross-Lib allows you to code for a sort of universal virtual machine.

**Comment by Fabrizio-Caruso** [comment]
@ikrananka, I am now closing this issue because I have addressed the main problem in Cross-lib. For the sound I am not sure I can do much right now.
