### ISSUE TITLE
corrections/clarifications in documentation

### ISSUE THREAD

**Issue by TechCowboy** [Fabrizio-Caruso/CROSS-LIB#290]
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/docs/EnglishArticle.md

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

Section: 

"xl chase gcc", which will build the game Chase in turn-based mode for the native console.
should be
"./xl chase gcc"

However it fails to build
![image](https://github.com/Fabrizio-Caruso/CROSS-LIB/assets/2847372/c68f8a9f-8377-43af-8dd9-2d896f05b437)

Extra character at the end of line 171 seems to be the issue

![image](https://github.com/Fabrizio-Caruso/CROSS-LIB/assets/2847372/92bb30a0-a73f-427d-8fa2-b5c8be7b3220)

but still fails

![image](https://github.com/Fabrizio-Caruso/CROSS-LIB/assets/2847372/37e63b8a-47a7-4865-81c2-cc8045ab60c5)

./xl build chase  
./xl chase
Both of these DO work

**Comment by Fabrizio-Caruso** [comment]
Hi! Thanks for showing interest in my project.
`xl chase` is the same as `./xl chase`, once the "." directory is in your path. I can add a note to clarify this.

For the extra character, you are right! I am going to fix it.
I am mostly testing Cross-Lib under Windows/Cygwin because it is easier to find emulators for Windows.
I need to run more tests under Linux proper.

**Comment by TechCowboy** [comment]
I guess I'll do the linux testing for you 😀

**Comment by Fabrizio-Caruso** [comment]
Fixed. Please run "git pull" to get the latest version. I have been able to run "xl bomber z88dk_targets" under Ubuntu.

Thanks again for reporting this issue.

Be aware that I am actively developing Cross-Lib almost every day. So it can be half-broken one day and fixed the next day.

P.S.: The targets found in Makefile_common are a fraction of the possible ones. I will add all the others eventually. Most of them are currently "hidden" in `src/games/chase/makefile.chase` and currently they are not meant to be used.

**Comment by Fabrizio-Caruso** [comment]
@TechCowboy is it good for you now (after git pull) ?

**Comment by Fabrizio-Caruso** [comment]
@TechCowboy 
P.S.:
Have you maned to add "." to the path.

This may be different on each operating system. 

In my Ubuntu version I just had to add:
`PATH=$PATH:.`
in the `.profile` file in my home directory.

![image](https://github.com/Fabrizio-Caruso/CROSS-LIB/assets/29057615/1f9137d3-2ebb-458c-99ec-585516fe28a3)


Under some systems it is already in the PATH environment variable.

**Comment by TechCowboy** [comment]
I've added . to my path and the example now comples if I use
xl chase
however, in the documentation under installation, it says use
xl chase gcc
which does not work.

![image](https://github.com/Fabrizio-Caruso/CROSS-LIB/assets/2847372/5a5a513c-3ea8-492a-886a-e601f53749d1)

**Comment by Fabrizio-Caruso** [comment]
@TechCowboy Thanks for seeing this.

I have change a bit the names of the  targets. I will have to update the doc accordingly.

(1) Default target is "ncurses", which is supposed to build the game/program for the host console (cygwin, linux bash, etc...) by using the default compiler (defined in `config.ini` "`native_compiler`" variable)+ ncurses. This should build a (sort of) "playable" native version of the game for any game. So this target requires both a native compiler (e.g., gcc) and ncurses.
Example:
`xl bomber` 
or equivalently
`xl bomber ncurses`

(2) For testing purposes or turn-based versions of some games (the game code has to be aware of it, though), we can even build the games/programs with just the default compiler without the need of ncurses and by just using the ANSI C standard library for input/output, which has no real-time interactive input. This is now done with the "stdio" target and no longer with "gcc", because "gcc" makes no sense as we can choose any compiler in `config.ini`.
As stdio has no support for immediate input, the game will be, at best, playable in turn-based mode. Most games won't be playable at all, because this can only work for games that are aware of this (e.g., chase) where the code invokes a refresh command to re-display the content of the screen like a slide-slow. This can be used to test if the games compile with a given compiler.

Example:
`xl chase stdio`
